### ISSUE TITLE
Cross Entropy loss or NLL loss

### ISSUE THREAD

**Issue by 07Agarg** [PRIS-CV/Fine-Grained-or-Not#1]
Hi, Thanks for the nice repo!

I just wanted clarification about the NLL criterion in the code. Are the results in Birds.out using Cross Entropy criterion or NLL criterion?

Also, I tried running the code as is (using NLL criterion), train and test loss becomes nan. 

Thanks once again.

**Comment by dongliangchang** [comment]
The results in Birds.out are using criterion_NLLLoss.
And I re-run the code in this repo, all thing is fine. 
Please check your environment and the data preparation.

**Comment by 07Agarg** [comment]
Thank you!
