### ISSUE TITLE
AIR和CAR数据集

### ISSUE THREAD

**Issue by JJJTF** [PRIS-CV/Fine-Grained-or-Not#12]
您好，非常感谢您可以分享代码，但是我在复现您论文中的实验结果的过程中发现AIR数据集和CAR数据集与论文所展示的结果相差特别大，是否air.xls和car,xls文件有错？
希望得到您的回复，再次感谢！

**Comment by dongliangchang** [comment]
请参考这个issue： #2 ，检查数据集的文件名。
