### ISSUE TITLE
How to evaluate the performance under the traditional FGVC setting?

### ISSUE THREAD

**Issue by yxhhxy7** [PRIS-CV/Fine-Grained-or-Not#3]
Hi,

Thanks for your amazing code and work!

What is the difference between the ACC of traditional FGVC setting and specie_acc? And how to change the code to evaluate the performance of the model under the traditional FGVC setting?

**Comment by dongliangchang** [comment]
Sorry for the late.  

```
Q: What is the difference between the ACC of traditional FGVC setting and specie_acc?
A: The ACC of traditional FGVC = specie_acc.
```
```
And how to change the code to evaluate the performance of the model under the traditional FGVC setting?
For a fair comparison, we need to modify the input to the model to 448*448. 
```
And for more training details, please see our other project: [PMG](https://github.com/PRIS-CV/PMG-Progressive-Multi-Granularity-Training)
