### ISSUE TITLE
Test set of CUB

### ISSUE THREAD

**Issue by Michael-Ray-Sirius** [PRIS-CV/Fine-Grained-or-Not#5]
Greetings!
Love this work
But I have a silly question, there are some strange species in sheet2 in birds.xlsx, what should I do?  Shoud I make some dir whose name is that ?

**Comment by dongliangchang** [comment]
I'm sorry, please delete sheet2 in birds.xlsx.

**Comment by Michael-Ray-Sirius** [comment]
> I'm sorry, please delete sheet2 in birds.xlsx.

Thank u for your reply. Another issue is that what should I do to split test set?  In bird.xlsx sheet1 is the train set label or test set label ?

**Comment by dongliangchang** [comment]
Please follow this issue #2
