### ISSUE TITLE
Selection of some parameters and loss

### ISSUE THREAD

**Issue by hit-dyl** [PRIS-CV/Fine-Grained-or-Not#7]
hi，this works very well, I have two questions
1. Why Hiden_Number is 600？
2. Why choose NLL loss，do not use CE loss directly？

**Comment by dongliangchang** [comment]
1. To make the three different tasks have the same number of features, we chose a number that is closer to 512 and divisible by 3. 
2. In torch, NLL(log(softmax(x))) ==CE(x)

**Comment by hit-dyl** [comment]
Got it, thank you
