### ISSUE TITLE
how to reach 94.3 accuracy on stanford-cars？

### ISSUE THREAD

**Issue by hit-dyl** [PRIS-CV/Fine-Grained-or-Not#9]
hi！When the image size is 224*224, the accuracy rate can reach about 89.4（species_acc）. When I change the image size to 448*448, the accuracy rate is less than 80. How to achieve the 94.3 accuracy rate in the paper? Have you modified any other training parameters（epoch or lr or batchsize or others）?

**Comment by dongliangchang** [comment]
Please follow the experimental setup in our another project https://github.com/PRIS-CV/PMG-Progressive-Multi-Granularity-Training
